# -*- coding: utf-8 -*-
"""RXI_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnZ4mFlDzmE0L5GtpHSpth-0dbrDvEys
"""


import streamlit as st
import pandas as pd
import networkx as nx
import plotly.express as px
import plotly.graph_objects as go
from streamlit_option_menu import option_menu
import matplotlib.pyplot as plt

# ------------------------
# Page Configuration
# ------------------------

st.set_page_config(
    page_title="Enterprise AI Governance Playbook",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ------------------------
# Custom Styling
# ------------------------

st.markdown("""
<style>

.main {
    background-color: #f5f7fa;
}

.stMetric {
    background-color: white;
    padding: 15px;
    border-radius: 10px;
}

h1, h2, h3 {
    color: #0A3D62;
}

.sidebar .sidebar-content {
    background-color: #0A3D62;
}

</style>
""", unsafe_allow_html=True)

# ------------------------
# Load Data
# ------------------------

@st.cache_data
def load_data():

    systems = pd.read_excel("AI_Governance_Playbook.xlsx", sheet_name="AI_Systems")
    risks = pd.read_excel("AI_Governance_Playbook.xlsx", sheet_name="Risks")
    controls = pd.read_excel("AI_Governance_Playbook.xlsx", sheet_name="Controls")

    return systems, risks, controls


systems, risks, controls = load_data()

# ------------------------
# Sidebar Navigation
# ------------------------

with st.sidebar:

    st.image("https://cdn-icons-png.flaticon.com/512/906/906334.png", width=80)

    selected = option_menu(
        menu_title="AI Governance Menu",
        options=[
            "Dashboard",
            "AI Systems",
            "Risk Management",
            "Control Framework",
            "Compliance Monitoring",
            "Governance Graph",
            "Framework Mapping"
        ],
        icons=[
            "speedometer",
            "cpu",
            "exclamation-triangle",
            "shield-check",
            "clipboard-check",
            "diagram-3",
            "layers"
        ],
        default_index=0
    )

# ------------------------
# Dashboard
# ------------------------

if selected == "Dashboard":

    st.title("Enterprise AI Governance Dashboard")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Total AI Systems", len(systems))
    col2.metric("Total Risks", len(risks))
    col3.metric("Total Controls", len(controls))
    col4.metric("Compliance Score", "92%")

    st.divider()

    # Risk distribution chart
    st.subheader("Risk Distribution")

    risk_count = risks["Risk_Type"].value_counts()

    fig = px.pie(
        values=risk_count.values,
        names=risk_count.index,
        title="Risk Type Distribution"
    )

    st.plotly_chart(fig, use_container_width=True)

    # Risk level distribution
    st.subheader("Risk Level Distribution")

    fig2 = px.histogram(
        systems,
        x="Risk_Level",
        color="Risk_Level",
        title="AI Systems by Risk Level"
    )

    st.plotly_chart(fig2, use_container_width=True)

# ------------------------
# AI Systems Page
# ------------------------

elif selected == "AI Systems":

    st.title("AI Systems Inventory")

    st.dataframe(systems, use_container_width=True)

    st.subheader("System Details")

    selected_system = st.selectbox(
        "Select AI System",
        systems["System_Name"]
    )

    system_details = systems[systems["System_Name"] == selected_system]

    col1, col2, col3 = st.columns(3)

    col1.metric("Risk Level", system_details["Risk_Level"].values[0])
    col2.metric("Owner", system_details["Owner"].values[0])
    col3.metric("Status", system_details["Status"].values[0])

# ------------------------
# Risk Management
# ------------------------

elif selected == "Risk Management":

    st.title("Risk Management (NIST AI RMF)")

    st.dataframe(risks)

    st.subheader("Risk Analysis")

    selected_system = st.selectbox(
        "Select System ID",
        risks["AI_System_ID"].unique()
    )

    system_risks = risks[risks["AI_System_ID"] == selected_system]

    st.dataframe(system_risks)

    st.subheader("Risk Severity Score")

    severity_map = {
        "Bias": 8,
        "Privacy": 9,
        "Security": 10,
        "Performance": 6
    }

    system_risks["Severity"] = system_risks["Risk_Type"].map(severity_map)

    fig = px.bar(
        system_risks,
        x="Risk_Type",
        y="Severity",
        color="Severity",
        title="Risk Severity Analysis"
    )

    st.plotly_chart(fig, use_container_width=True)

# ------------------------
# Control Framework
# ------------------------

elif selected == "Control Framework":

    st.title("Unified Control Framework")

    st.dataframe(controls)

    st.subheader("Control Effectiveness")

    effectiveness = {
        "Bias Testing": 95,
        "Access Control": 98,
        "Encryption": 97
    }

    controls["Effectiveness"] = controls["Control_Name"].map(effectiveness)

    fig = px.bar(
        controls,
        x="Control_Name",
        y="Effectiveness",
        color="Effectiveness"
    )

    st.plotly_chart(fig, use_container_width=True)

# ------------------------
# Compliance Monitoring
# ------------------------

elif selected == "Compliance Monitoring":

    st.title("Compliance Monitoring")

    compliance_data = pd.DataFrame({

        "Framework": [
            "India AI Governance",
            "NIST AI RMF",
            "Unified Control Framework"
        ],

        "Compliance %": [
            90,
            95,
            92
        ]
    })

    fig = px.bar(
        compliance_data,
        x="Framework",
        y="Compliance %",
        color="Compliance %"
    )

    st.plotly_chart(fig, use_container_width=True)

# ------------------------
# Governance Graph
# ------------------------

elif selected == "Governance Graph":

    st.title("AI Governance Network Graph")

    G = nx.Graph()

    for index, row in risks.iterrows():
        G.add_edge(row["AI_System_ID"], row["Risk_Type"])

    for index, row in controls.iterrows():
        G.add_edge(row["Risk_Type"], row["Control_Name"])

    fig, ax = plt.subplots(figsize=(12, 8))

    nx.draw(
        G,
        with_labels=True,
        node_color="lightblue",
        node_size=2500,
        font_size=10
    )

    st.pyplot(fig)

# ------------------------
# Framework Mapping
# ------------------------

elif selected == "Framework Mapping":

    st.title("Framework Integration Mapping")

    mapping_data = pd.DataFrame({

        "Framework": [
            "India AI Governance",
            "NIST AI RMF",
            "Unified Control Framework"
        ],

        "Purpose": [
            "Governance Policy",
            "Risk Management",
            "Control Implementation"
        ]
    })

    st.dataframe(mapping_data)
